---
output: html_document
params: 
 input : NA
 get_title: NA
 
---

---
title: `r params$get_title`
---

<head>
  <style>
      priority1 {
                  font-size: 75%;
                  color: #7DCEA0;
                }
                priority2 {
                  font-size: 100%;
                  color: #52BE80;
                }
                priority3 {
                  font-size: 125%;
                  color: #27AE60;
                }
                priority4 {
                  font-size: 150%;
                  color: #229954;
                }
                priority5 {
                  font-size: 175%;
                  color: #1E8449;
                  font-weight: bold;
                }
  </style>
</head>


```{r include=FALSE}

col_title = paste(strsplit(params$get_title,split = " ")[[1]],collapse = " ")

table <- data.frame(unlist(params$input))
table <- data.frame(1:nrow(table)
                    ,unlist(params$input))

# colnames(table) <- c("Cluster No", col_title)

colnames(table)[1] <- "Cluster no."
colnames(table)[2] <- "Frequency"

# k=1
#  for ( i in seq(2,length(params$input),2) ){
#     table2[k][i] = t(data.frame(params$input[[i]]))
#        }


```



```{r echo = FALSE}

knitr::kable(table, row.names = F,
              align = 'l', caption = "Events along with their weights are as follows:")

# knitr::params$input

# for(k in 1:i/2){
  # knitr::kable(table2[2], row.names = F,
              # align = 'l')
# }

# params$input
```

