# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' calculate_sorenson_distance_cpp
#' @description
#' Calculates x
#'
#' @param itemset_1 a vector of intertime values
#' @param itemset_2 a vector of intertime values
#'
#'
#' @details
#' \code{session_count} takes a vector of intertime values (generated via \code{\link{intertimes}},
#' or in any other way you see fit) and returns the total number of sessions within that dataset.
#' It's implimented in C++, providing a (small) increase in speed over the R equivalent.
#' @export
calculate_sorenson_distance_cpp <- function(itemset_1, itemset_2) {
    .Call('approxmapR_calculate_sorenson_distance_cpp', PACKAGE = 'approxmapR', itemset_1, itemset_2)
}

#' @title
#' dist_bw_sequences_cpp
#' @description
#' Calculates x
#'
#' @param sequence_1 a vector of intertime values
#' @param sequence_2 a vector of intertime values
#'
#'
#' @details
#' \code{session_count} takes a vector of intertime values (generated via \code{\link{intertimes}},
#' or in any other way you see fit) and returns the total number of sessions within that dataset.
#' It's implimented in C++, providing a (small) increase in speed over the R equivalent.
#' @export
dist_bw_sequences_cpp <- function(sequence_1, sequence_2) {
    .Call('approxmapR_dist_bw_sequences_cpp', PACKAGE = 'approxmapR', sequence_1, sequence_2)
}

#' @title
#' calculate_distance_bw_sequences_cpp
#' @description
#' Calculates x
#'
#' @param sequences a list of intertime values
#'
#' @details
#' \code{session_count} takes a vector of intertime values (generated via \code{\link{intertimes}},
#' or in any other way you see fit) and returns the total number of sessions within that dataset.
#' It's implimented in C++, providing a (small) increase in speed over the R equivalent.
#' @export
calculate_distance_bw_sequences_cpp <- function(sequences) {
    .Call('approxmapR_calculate_distance_bw_sequences_cpp', PACKAGE = 'approxmapR', sequences)
}

